image: docker:19-git

services:
  - docker:19-dind

stages:
  - init
  - test
  - build
  - package
  - deploy

install:
  stage: init
  image: node:13
  script:
    # Install node modules
    - cd power
    - npm install
  artifacts:
    expire_in: 1 week
    paths:
      - power/node_modules/
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - power/node_modules/
  only:
    - merge_requests
    - dev
    - staging

test:karma:
  stage: test
  image: node:13
  before_script:
    # Install chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
  script:
    # Run Karma tests
    - cd power
    - node_modules/@angular/cli/bin/ng test --browsers ChromeHeadlessNoSandbox --progress false --watch false --code-coverage
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    reports:
      junit: power/output/junit_karma.xml
    paths:
      - power/output/junit_karma.xml
  only:
    - merge_requests
    - dev
    - staging

test:e2e:
  stage: test
  image: node:13
  allow_failure: true
  before_script:
    # Install chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install google-chrome-stable -y
  script:
    # Run E2E tests
    - cd power
    - node_modules/@angular/cli/bin/ng e2e --protractor-config e2e/protractor-ci.conf.js
  artifacts:
    reports:
      junit: power/output/junit_e2e.xml
    paths:
      - power/output/junit_e2e.xml
  only:
    - merge_requests
    - dev
    - staging

test:audit:
  stage: test
  image: node:13
  allow_failure: true
  script:
    - cd power
    - npm audit
  only:
    - merge_requests
    - dev
    - staging

test:lint:
  stage: test
  image: node:13
  allow_failure: true
  script:
    - cd power
    - npm run lint
  only:
    - merge_requests
    - dev
    - staging

test:lint:styles:
  stage: test
  image: node:13
  allow_failure: true
  script:
    - cd power
    - npm run lint:styles
  only:
    - merge_requests
    - dev
    - staging

build:
  stage: build
  image: node:13
  script:
    - cd power
    - npm run build -- --prod
  artifacts:
    expire_in: 1 week
    paths:
      - power/dist/power
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - power/dist/
  only:
    - dev
    - staging

package:
  stage: package
  image: docker
  dependencies:
    - build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - dev
    - staging

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.1.2
  dependencies:
    - package
  script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
    - helm upgrade power ./chart/power -n "$CI_COMMIT_REF_NAME" --install --set=image.tag="$CI_COMMIT_SHORT_SHA"
  only:
    - dev
    - staging
