image: de.icr.io/lgln/kube-tools:latest

services:
  - docker:dind

stages:
  - init
  - test
  - build
  - package
  - scan
  - deploy

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - power/node_modules/
  policy: pull-push

init:npm:
  stage: init
  image: node:lts-alpine
  interruptible: true
  cache:
    <<: *global_cache
  script:
    - cd power
    - npm ci
    - node_modules/.bin/ngcc --tsconfig ./src/tsconfig.app.json -p es2015
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

init:npm-branches:
  stage: init
  image: node:lts-alpine
  interruptible: true
  cache:
    <<: *global_cache
  script:
    - cd power
    - npm ci
    - node_modules/.bin/ngcc --tsconfig ./src/tsconfig.app.json -p es2015
  only:
    - branches
  except:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  when: manual

init:helm-dev:
  stage: init
  interruptible: true
  cache: {}
  script:
    - helm template power ./chart/power -f ./chart/power/values-dev.yaml --dependency-update --output-dir manifest-dev
  artifacts:
    name: "manifest"
    expire_in: 2 hrs
    public: false
    paths:
      - manifest-dev
  only:
    - merge_requests
    - tags
    - dev

init:helm-staging:
  stage: init
  interruptible: true
  cache: {}
  script:
    - helm template power ./chart/power -f ./chart/power/values-staging.yaml --dependency-update --output-dir manifest-staging
  artifacts:
    name: "manifest"
    expire_in: 2 hrs
    public: false
    paths:
      - manifest-staging
  only:
    - staging

init:helm-production:
  stage: init
  interruptible: true
  cache: {}
  script:
    - helm template power ./chart/power -f ./chart/power/values-production.yaml --dependency-update --output-dir manifest-production
  artifacts:
    name: "manifest"
    expire_in: 2 hrs
    public: false
    paths:
      - manifest-production
  only:
    - production

test:karma:
  stage: test
  image: trion/ng-cli-karma:latest
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng test --browsers ChromeHeadlessNoSandbox --progress false --watch false --code-coverage
  artifacts:
    expire_in: 2 days
    public: false
    reports:
      junit: power/output/junit_karma.xml
    paths:
      - power/output/junit_karma.xml
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:e2e:
  stage: test
  image: trion/ng-cli-e2e:latest
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/protractor/bin/webdriver-manager update --versions.chrome 91.0.4472.77 --gecko false --standalone false
    - node_modules/@angular/cli/bin/ng e2e -c staging --webdriver-update=false
  artifacts:
    expire_in: 2 days
    public: false
    reports:
      junit: power/output/junit_e2e.xml
    paths:
      - power/output/junit_e2e.xml
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  when: manual

test:audit:
  stage: test
  image: node:lts-alpine
  interruptible: true
  needs: []
  dependencies: []
  cache: {}
  script:
    - cd power
    - npm audit
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  allow_failure: true

test:lint:
  stage: test
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng lint power
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:lint-html:
  stage: test
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run lint:html
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:lint-styles:
  stage: test
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run lint:styles
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:helm-dry-run:
  stage: test
  interruptible: true
  needs: []
  dependencies: []
  cache: {}
  before_script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
  script:
    - helm upgrade power ./chart/power -n dev -f ./chart/power/values-dev.yaml --install --dry-run
  only:
    - dev
    - staging
    - production

test:kubesec-dev:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-dev
      artifacts: true
  dependencies:
    - init:helm-dev
  cache: {}
  script:
    - cat manifest-dev/power/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-dev/power/templates/*.yaml | kubesec-check.sh -
  only:
    - merge_requests
    - tags
    - dev

test:kubesec-staging:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-staging
      artifacts: true
  dependencies:
    - init:helm-staging
  cache: {}
  script:
    - cat manifest-staging/power/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-staging/power/templates/*.yaml | kubesec-check.sh -
  only:
    - staging

test:kubesec-production:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-production
      artifacts: true
  dependencies:
    - init:helm-production
  cache: {}
  script:
    - cat manifest-production/power/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-production/power/templates/*.yaml | kubesec-check.sh -
  only:
    - production

test:kube-linter-dev:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-dev
      artifacts: true
  dependencies:
    - init:helm-dev
  cache: {}
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-dev/power/templates/*.yaml
  only:
    - merge_requests
    - tags
    - dev
  allow_failure: true

test:kube-linter-staging:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-staging
      artifacts: true
  dependencies:
    - init:helm-staging
  cache: {}
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-staging/power/templates/*.yaml
  only:
    - staging
  allow_failure: true

test:kube-linter-production:
  stage: test
  interruptible: true
  needs:
    - job: init:helm-production
      artifacts: true
  dependencies:
    - init:helm-production
  cache: {}
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-production/power/templates/*.yaml
  only:
    - production
  allow_failure: true

build:branches:
  stage: build
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm-branches
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng run power:prerender:staging
  artifacts:
    name: "compiled dist"
    expire_in: 2 days
    public: false
    paths:
      - power/dist/power/browser
  only:
    - branches
  except:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  when: manual

build:
  stage: build
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng run power:prerender:staging
  artifacts:
    name: "compiled dist"
    expire_in: 2 days
    public: false
    paths:
      - power/dist/power/browser
  only:
    - merge_requests
    - tags
    - dev
    - staging

build:production:
  stage: build
  image: node:lts-alpine
  interruptible: true
  needs:
    - job: init:npm
      artifacts: false
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng run power:prerender:de
  artifacts:
    name: "compiled dist"
    expire_in: 2 days
    public: false
    paths:
      - power/dist/power/browser
  only:
    - production

package:branches:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  interruptible: false
  dependencies:
    - build:branches
  cache: {}
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME"
  only:
    - branches
  except:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  when: manual

package:development:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  interruptible: false
  dependencies:
    - build
  cache: {}
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME"
  only:
    - dev

package:staging:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  interruptible: false
  dependencies:
    - build
  cache: {}
  environment:
    name: staging
    action: prepare
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:staging --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME"
  only:
    - staging

package:production:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  interruptible: false
  dependencies:
    - build:production
  cache: {}
  environment:
    name: production
    action: prepare
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:production --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME"
  only:
    - production
  when: manual
  allow_failure: false

scan:development:
  stage: scan
  interruptible: false
  needs:
    - job: package:development
      artifacts: false
  dependencies: []
  cache: {}
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info &> /dev/null && break; sleep 5; i=$(( i + 1 )) ; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:latest"
    - trivy image --no-progress --ignore-unfixed --exit-code 1 "$CI_REGISTRY_IMAGE:latest"
  only:
    - dev
  allow_failure: true

scan:staging:
  stage: scan
  interruptible: false
  needs:
    - job: package:staging
      artifacts: false
  dependencies: []
  cache: {}
  environment:
    name: staging
    action: prepare
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info &> /dev/null && break; sleep 5; i=$(( i + 1 )) ; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:staging"
    - trivy image --no-progress --ignore-unfixed --exit-code 1 "$CI_REGISTRY_IMAGE:staging"
  only:
    - staging
  allow_failure: true

scan:production:
  stage: scan
  interruptible: false
  needs:
    - job: package:production
      artifacts: false
  dependencies: []
  cache: {}
  environment:
    name: production
    action: prepare
  before_script:
    - i=0; while [ "$i" -lt 12 ]; do docker info &> /dev/null && break; sleep 5; i=$(( i + 1 )) ; done
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:production"
    - trivy image --no-progress --ignore-unfixed --exit-code 1 "$CI_REGISTRY_IMAGE:production"
  only:
    - production
  allow_failure: true

deploy:development:
  stage: deploy
  interruptible: false
  needs:
    - job: package:development
      artifacts: false
  dependencies: []
  cache: {}
  before_script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
  script:
    - helm upgrade power ./chart/power -n dev -f ./chart/power/values-dev.yaml --install
      --set-string labels.commit="$CI_COMMIT_SHORT_SHA"
      --set-string annotations.deployedAt="$CI_JOB_STARTED_AT"
  only:
    - dev

deploy:staging:
  stage: deploy
  interruptible: false
  needs:
    - job: package:staging
      artifacts: false
  dependencies: []
  cache: {}
  environment:
    name: staging
    action: start
  before_script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
  script:
    - helm upgrade power ./chart/power -n staging -f ./chart/power/values-staging.yaml --install
      --set-string labels.commit="$CI_COMMIT_SHORT_SHA"
      --set-string annotations.deployedAt="$CI_JOB_STARTED_AT"
  only:
    - staging

deploy:production:
  stage: deploy
  interruptible: false
  needs:
    - job: package:production
      artifacts: false
  dependencies: []
  cache: {}
  environment:
    name: production
    action: start
  before_script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
  script:
    - helm upgrade power ./chart/power -n prod -f ./chart/power/values-production.yaml --install
      --set-string labels.commit="$CI_COMMIT_SHORT_SHA"
      --set-string annotations.deployedAt="$CI_JOB_STARTED_AT"
  only:
    - production
