image: docker:stable

services:
  - docker:stable-dind

stages:
  - init
  - test
  - build
  - package
  - deploy

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - power/node_modules/
    - manifest-dev/
    - manifest-staging/
    - manifest-production/
  policy: pull-push

install:
  stage: init
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
  script:
    # install node modules
    - cd power
    - npm ci
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

init:helm-dev:
  stage: init
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
  script:
    - helm template power ./chart/power -f ./chart/power/values-dev.yaml --dependency-update --output-dir manifest-dev
  only:
    - merge_requests
    - tags
    - dev

init:helm-staging:
  stage: init
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
  script:
    - helm template power ./chart/power -f ./chart/power/values-staging.yaml --dependency-update --output-dir manifest-staging
  only:
    - staging

init:helm-production:
  stage: init
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
  script:
    - helm template power ./chart/power -f ./chart/power/values-production.yaml --dependency-update --output-dir manifest-production
  only:
    - production

test:karma:
  stage: test
  image: trion/ng-cli-karma:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    # Run Karma tests
    - cd power
    - node_modules/@angular/cli/bin/ng test --browsers ChromeHeadlessNoSandbox --progress false --watch false --code-coverage
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    expire_in: 2 weeks
    reports:
      junit: power/output/junit_karma.xml
    paths:
      - power/output/junit_karma.xml
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:e2e:
  stage: test
  image: trion/ng-cli-e2e:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    # Run E2E tests
    - cd power
    - node_modules/@angular/cli/bin/ng e2e --protractor-config e2e/protractor-ci.conf.js
  artifacts:
    expire_in: 2 weeks
    reports:
      junit: power/output/junit_e2e.xml
    paths:
      - power/output/junit_e2e.xml
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  when: manual

test:audit:
  stage: test
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm audit
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production
  allow_failure: true

test:lint:
  stage: test
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - node_modules/@angular/cli/bin/ng lint power
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:lint-html:
  stage: test
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run lint:html
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:lint-styles:
  stage: test
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run lint:styles
  only:
    - merge_requests
    - tags
    - dev
    - staging
    - production

test:helm-dry-run:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache: {}
  script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
    - helm upgrade power ./chart/power -n dev -f ./chart/power/values-dev.yaml --install --set=image.tag="$CI_COMMIT_SHORT_SHA" --dry-run
  only:
    - dev
    - staging
    - production

test:kubesec-dev:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cat manifest-dev/power/templates/*.yaml manifest-dev/power/charts/*/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-dev/power/templates/*.yaml manifest-dev/power/charts/*/templates/*.yaml | kubesec-check.sh -
  only:
    - merge_requests
    - tags
    - dev

test:kubesec-staging:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cat manifest-staging/power/templates/*.yaml manifest-staging/power/charts/*/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-staging/power/templates/*.yaml manifest-staging/power/charts/*/templates/*.yaml | kubesec-check.sh -
  only:
    - staging

test:kubesec-production:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cat manifest-production/power/templates/*.yaml manifest-production/power/charts/*/templates/*.yaml | kubesec-scan.sh -
    - cat manifest-production/power/templates/*.yaml manifest-production/power/charts/*/templates/*.yaml | kubesec-check.sh -
  only:
    - production

test:kube-linter-dev:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-dev/power/templates/*.yaml
  only:
    - merge_requests
    - tags
    - dev
  allow_failure: true

test:kube-linter-staging:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-staging/power/templates/*.yaml
  only:
    - staging

test:kube-linter-production:
  stage: test
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - kube-linter lint -v --add-all-built-in --exclude required-annotation-email,required-label-owner manifest-production/power/templates/*.yaml
  only:
    - production

build:
  stage: build
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run build -- -c staging
  artifacts:
    name: "compiled dist"
    expire_in: 2 days
    paths:
      - power/dist/power
  only:
    - merge_requests
    - tags
    - dev
    - staging

build:prod:
  stage: build
  image: node:lts-alpine
  dependencies: []
  cache:
    <<: *global_cache
    policy: pull
  script:
    - cd power
    - npm run build -- --prod
  artifacts:
    name: "compiled dist"
    expire_in: 2 days
    paths:
      - power/dist/power
  only:
    - production

package:
  stage: package
  image: de.icr.io/lgln/kube-tools:latest
  dependencies:
    - build
    - build:prod
  cache: {}
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" --build-arg=COMMIT="$CI_COMMIT_SHORT_SHA" --build-arg=BRANCH="$CI_COMMIT_REF_NAME" .
    - trivy image --no-progress --exit-code 1 "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only:
    - dev
    - staging
    - production

deploy:development:
  stage: deploy
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache: {}
  script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
    - helm upgrade power ./chart/power -n dev -f ./chart/power/values-dev.yaml --install --set=image.tag="$CI_COMMIT_SHORT_SHA"
  only:
    - dev

deploy:staging:
  stage: deploy
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache: {}
  environment: staging
  script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
    - helm upgrade power ./chart/power -n staging -f ./chart/power/values-staging.yaml --install --set=image.tag="$CI_COMMIT_SHORT_SHA"
  only:
    - staging

deploy:production:
  stage: deploy
  image: de.icr.io/lgln/kube-tools:latest
  dependencies: []
  cache: {}
  environment: production
  script:
    - kubectl config set-cluster k8s --server="$KUBE_API_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials "$KUBE_DEPLOY_SECRET_NAME" --token="$KUBE_API_TOKEN"
    - kubectl config set-context default --cluster=k8s --user="$KUBE_DEPLOY_SECRET_NAME"
    - kubectl config use-context default
    - helm upgrade power ./chart/power -n prod -f ./chart/power/values-prod.yaml --install --set=image.tag="$CI_COMMIT_SHORT_SHA" --set replicaCount=1
  only:
    - production
  when: manual
