# Default values for power.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: de.icr.io/power/power
  pullPolicy: Always
  tag: "production"

imagePullSecrets:
  - name: de-icr-io
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/override: power-https-redirect
    konghq.com/plugins: power-rate-limiting-by-ip,power-cors
  hosts:
    - host: prod.power-production-65655d4c73bf47a3300821aa2939abf4-0000.eu-de.containers.appdomain.cloud
      paths:
        - path: /
          serviceName: power
          servicePort: 80
    - host: power.lgln.niedersachsen.de
      paths:
        - path: /
          serviceName: power
          servicePort: 80
  tls:
    - secretName: power-production-65655d4c73bf47a3300821aa2939abf4-0000
      hosts:
        - prod.power-production-65655d4c73bf47a3300821aa2939abf4-0000.eu-de.containers.appdomain.cloud
    - secretName: sub-lgln-niedersachsen-de
      hosts:
        - power.lgln.niedersachsen.de

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  modules:
    - "immobilienpreisindex"
    - "bodenrichtwerte"
    - "immobilienpreiskalkulator"
    - "grundstuecksmarktdaten"
    - "feedback"
  authentication: true
