{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "power.fullname" . }}
  labels:
    {{- include "power.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      {{- include "power.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.from }}
  ingress:
    {{- with .Values.networkPolicy.from }}
    - from:
        {{- toYaml . | nindent 8 }}
      ports:
        - protocol: TCP
          port: 8081
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - from:
        - podSelector:
            matchLabels:
              app: prometheus
          namespaceSelector:
            matchLabels:
              name: prometheus
      ports:
        - protocol: TCP
          port: 9113
    {{- end }}
  {{- end }}
{{- end }}

---
{{- if .Values.defaultDenyNetworkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    {{- include "power.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
